`np.einsum`

`np.cov(x, y, ddof=1)`

`np.linalg.inv(np.dot(X.T, X))`

In [1]:
import numpy as np

# Inverse of a matrix, M$^{-1}$

```
np.linalg.inv(a)



Compute the (multiplicative) inverse of a matrix.

Given a square matrix `a`, return the matrix `ainv` satisfying
``dot(a, ainv) = dot(ainv, a) = eye(a.shape[0])``.

Parameters
----------
a : (..., M, M) array_like
    Matrix to be inverted.

Returns
-------
ainv : (..., M, M) ndarray or matrix
    (Multiplicative) inverse of the matrix `a`.
    
```

In [62]:
M = np.matrix([[4,7],[2,6]])
M

matrix([[4, 7],
        [2, 6]])

This is not the inverse of a matrix:

In [63]:
1./M

matrix([[0.25      , 0.14285714],
        [0.5       , 0.16666667]])

This is:

In [64]:
M**-1

matrix([[ 0.6, -0.7],
        [-0.2,  0.4]])

So is this:

In [65]:
np.linalg.inv(M)

matrix([[ 0.6, -0.7],
        [-0.2,  0.4]])