In [1]:
import numpy as np
import pandas as pd

import lnr

import matplotlib.pyplot as plt
%matplotlib inline

from Zoldak.Math.tools import to_log

In [2]:
data = pd.read_csv(('/Users/kimzoldak/Github/GRB_Hubble_Diagram/data/'
                    'Band_13_GBM+LAT__22_GBMconstrained.txt'), 
                   sep='\t')

data = data[data.trigger.map(lambda x: x != 'bn090510016')]  # remove short burst
data.index = range(0, len(data))

df = pd.DataFrame()
df['eiso'] = data['eiso']/1E52
df['eiso_err'] = data.loc[:, ['eiso_err_low', 'eiso_err_up']].apply(np.mean, 1)
df['eiso_err'] = df['eiso_err']/1E52
df['epeakRest'] = data['epeakRest']
df['epeakRest_err'] = data.loc[:, ['epeakRest_err_low', 'epeakRest_err_up']].apply(np.mean, 1)


x, xerr = to_log(df['eiso'], df['eiso_err'], which='average', errTypeReturn='moe')
y, yerr = to_log(df['epeakRest'], df['epeakRest_err'], which='average', errTypeReturn='moe')

In [6]:
?lnr.bces

In [7]:
lnr.bces(x1 = x, 
         x2 = y,  
         x1err = xerr,  
         x2err= yerr, 
         cerr=[], 
         logify=False, 
         model='yx', 
         bootstrap=5000, 
         verbose='normal', 
         full_output=True)

Fit                   B          err(B)
         A          err(A)
BCES(Y|X)          5.57e-01 +/- 6.09e-02     1.931e+00 +/- 1.018e-01
bootstrap          5.57e-01 +/- 6.21e-02    %10.3e +/- %9.3e

BCES(X|Y)          7.48e-01 +/- 5.57e-02     1.687e+00 +/- 8.722e-02
bootstrap          7.52e-01 +/- 6.26e-02    %10.3e +/- %9.3e

BCES Bisector      6.48e-01 +/- 7.64e-02     1.814e+00 +/- 1.200e-01
bootstrap          6.50e-01 +/- 5.17e-02    %10.3e +/- %9.3e

BCES Orthogonal    6.05e-01 +/- 6.06e-02     1.870e+00 +/- 1.020e-01
bootstrap          6.05e-01 +/- 6.26e-02    %10.3e +/- %9.3e



((1.9310691832986322, 0.1030328906677084),
 (0.5567468232928803, 0.06212707015913713),
 array([[ 0.3632883 , -0.20303876],
        [-0.20303876,  0.13011868]]))

In [9]:
lnr.bces(x1 = x, 
         x2 = y,  
         x1err = xerr,  
         x2err= yerr, 
         cerr=[], 
         logify=False, 
         model='xy', 
         bootstrap=5000, 
         verbose='normal', 
         full_output=True)

Fit                   B          err(B)
         A          err(A)
BCES(Y|X)          5.57e-01 +/- 6.09e-02     1.931e+00 +/- 1.018e-01
bootstrap          5.58e-01 +/- 6.22e-02    %10.3e +/- %9.3e

BCES(X|Y)          7.48e-01 +/- 5.57e-02     1.687e+00 +/- 8.722e-02
bootstrap          7.53e-01 +/- 6.21e-02    %10.3e +/- %9.3e

BCES Bisector      6.48e-01 +/- 7.64e-02     1.814e+00 +/- 1.200e-01
bootstrap          6.51e-01 +/- 5.10e-02    %10.3e +/- %9.3e

BCES Orthogonal    6.05e-01 +/- 6.06e-02     1.870e+00 +/- 1.020e-01
bootstrap          6.06e-01 +/- 6.21e-02    %10.3e +/- %9.3e



((1.687164029719201, 0.09360339409637033),
 (0.747685173607265, 0.062092493889721455),
 array([[ 0.26648115, -0.14401174],
        [-0.14401174,  0.10869207]]))

In [10]:
lnr.bces(x1 = x, 
         x2 = y,  
         x1err = xerr,  
         x2err= yerr, 
         cerr=[], 
         logify=False, 
         model='bi', 
         bootstrap=5000, 
         verbose='normal', 
         full_output=True)

Fit                   B          err(B)
         A          err(A)
BCES(Y|X)          5.57e-01 +/- 6.09e-02     1.931e+00 +/- 1.018e-01
bootstrap          5.57e-01 +/- 6.23e-02    %10.3e +/- %9.3e

BCES(X|Y)          7.48e-01 +/- 5.57e-02     1.687e+00 +/- 8.722e-02
bootstrap          7.53e-01 +/- 6.39e-02    %10.3e +/- %9.3e

BCES Bisector      6.48e-01 +/- 7.64e-02     1.814e+00 +/- 1.200e-01
bootstrap          6.50e-01 +/- 5.16e-02    %10.3e +/- %9.3e

BCES Orthogonal    6.05e-01 +/- 6.06e-02     1.870e+00 +/- 1.020e-01
bootstrap          6.05e-01 +/- 6.25e-02    %10.3e +/- %9.3e



((1.8144201435812346, 0.08925532624413891),
 (0.648064185318786, 0.051623333371461744),
 array([[ 0.50456411, -0.30409542],
        [-0.30409542,  0.20445352]]))

In [11]:
lnr.bces(x1 = x, 
         x2 = y,  
         x1err = xerr,  
         x2err= yerr, 
         cerr=[], 
         logify=False, 
         model='orth', 
         bootstrap=5000, 
         verbose='normal', 
         full_output=True)

Fit                   B          err(B)
         A          err(A)
BCES(Y|X)          5.57e-01 +/- 6.09e-02     1.931e+00 +/- 1.018e-01
bootstrap          5.58e-01 +/- 6.26e-02    %10.3e +/- %9.3e

BCES(X|Y)          7.48e-01 +/- 5.57e-02     1.687e+00 +/- 8.722e-02
bootstrap          7.50e-01 +/- 6.22e-02    %10.3e +/- %9.3e

BCES Bisector      6.48e-01 +/- 7.64e-02     1.814e+00 +/- 1.200e-01
bootstrap          6.49e-01 +/- 5.17e-02    %10.3e +/- %9.3e

BCES Orthogonal    6.05e-01 +/- 6.06e-02     1.870e+00 +/- 1.020e-01
bootstrap          6.05e-01 +/- 6.27e-02    %10.3e +/- %9.3e



((1.8696257896413782, 0.10358100960591397),
 (0.6048470788654332, 0.06273658275790171),
 array([[ 0.36446911, -0.20198149],
        [-0.20198149,  0.12849789]]))

In [11]:
lnr.mle?

In [4]:
lnr.mle(x1 = x, 
         x2 = y,  
         x1err = xerr,  
         x2err= yerr,  
         cerr=[], 
         s_int=True, 
         start=(1.0, 1.0, 0.1), 
         bootstrap=1000, 
         logify=False)

AttributeError: 'numpy.ndarray' object has no attribute 'array'